In [2]:
import torch
from torch.nn.utils.rnn import pad_sequence

In [4]:
vocab_size = 1000
# 定义3个长度不同的id序列
seq1 = torch.randint(vocab_size, (10, ))
seq2 = torch.randint(vocab_size, (5, ))
seq3 = torch.randint(vocab_size, (13, ))
print(seq1)
print(seq2)
print(seq3)

tensor([299, 698, 498, 547, 937, 777,   5, 311, 679, 807])
tensor([ 54, 606, 401, 616, 111])
tensor([789, 640, 937, 158, 446, 162, 169, 808, 612, 236, 556, 747, 634])


In [5]:
# 构建一批数据的列表
seq_list = [seq1, seq2, seq3]
print(seq_list)

[tensor([299, 698, 498, 547, 937, 777,   5, 311, 679, 807]), tensor([ 54, 606, 401, 616, 111]), tensor([789, 640, 937, 158, 446, 162, 169, 808, 612, 236, 556, 747, 634])]


In [9]:
# 填充，并合并成一个tensor
batch = pad_sequence(seq_list, batch_first=True, padding_value=0)
print(batch)
print(batch.shape)

tensor([[299, 698, 498, 547, 937, 777,   5, 311, 679, 807,   0,   0,   0],
        [ 54, 606, 401, 616, 111,   0,   0,   0,   0,   0,   0,   0,   0],
        [789, 640, 937, 158, 446, 162, 169, 808, 612, 236, 556, 747, 634]])
torch.Size([3, 13])
