In [1]:
import torch
import torch.nn as nn

## 定义RNN层

In [2]:
# 1. 定义单层单向RNN层（模型）
rnn = nn.RNN(
    input_size=3,
    hidden_size=4,
    batch_first=True,
)

In [9]:
# 1. 定义两层双向RNN层（模型）
rnn2 = nn.RNN(
    input_size=3,
    hidden_size=4,
    batch_first=True,
    num_layers=2,
    bidirectional=True,
)

## 前向传播

In [3]:
# 1. 定义输入: (N, L, input_size)
input = torch.randn(2, 4, 3) # 以“文武双全”“玉树临风” 两条数据为例，每个句子有4个词（序列长度为4），每个词用3维向量表示

In [4]:
# 2. 前向传播
output, hn = rnn(input)

In [5]:
print(output.shape) # [2, 4, 4] 2表示batch_size，4表示序列长度，4表示hidden_size
print(hn.shape) # [1, 2, 4] 1表示单层，2表示batch_size，4表示hidden_size

torch.Size([2, 4, 4])
torch.Size([1, 2, 4])


In [6]:
print(output)

tensor([[[ 0.3622,  0.7705, -0.3848,  0.6052],
         [ 0.4829,  0.1884, -0.7069,  0.7199],
         [ 0.5320,  0.6783, -0.8568,  0.8426],
         [ 0.3622, -0.5069, -0.7394,  0.6044]],

        [[ 0.0354, -0.5853, -0.1356,  0.4936],
         [ 0.4188,  0.7448, -0.6664,  0.5677],
         [ 0.4670, -0.3180, -0.7662,  0.7045],
         [ 0.3712,  0.8611, -0.7743,  0.8025]]], grad_fn=<TransposeBackward1>)


In [7]:
print(hn)

tensor([[[ 0.3622, -0.5069, -0.7394,  0.6044],
         [ 0.3712,  0.8611, -0.7743,  0.8025]]], grad_fn=<StackBackward0>)


In [10]:
# 两层双向RNN前向传播
output, hn = rnn2(input)
print(output.shape) #[2, 4, 8] 2表示batch_size，4表示序列长度，8表示hidden_size*2（双向）
print(hn.shape) #[4, 2, 4] 4表示num_layers*2（双向），2表示batch_size，4表示hidden_size

torch.Size([2, 4, 8])
torch.Size([4, 2, 4])


In [11]:
print(output)

tensor([[[ 0.4366, -0.3462, -0.4683,  0.5417, -0.3079, -0.6252,  0.5338,
          -0.7507],
         [ 0.0717, -0.5651,  0.0319,  0.7645,  0.0184, -0.3315,  0.5864,
          -0.3729],
         [ 0.1893, -0.5749, -0.5106,  0.7690,  0.4386, -0.3551,  0.4902,
          -0.3138],
         [-0.1046, -0.7555, -0.1188,  0.8034,  0.5755, -0.2963,  0.3786,
           0.3950]],

        [[ 0.1073, -0.2849,  0.1242,  0.7679,  0.2780, -0.2406,  0.4578,
           0.1843],
         [ 0.4100, -0.9243, -0.6802,  0.8297,  0.4882, -0.3767,  0.3136,
          -0.2346],
         [-0.2338, -0.7503,  0.1023,  0.8219,  0.6111, -0.3043,  0.3305,
           0.3982],
         [ 0.2836, -0.4708, -0.4678,  0.7332,  0.0407, -0.5951,  0.4946,
          -0.4690]]], grad_fn=<TransposeBackward1>)


In [12]:
print(hn)

tensor([[[-3.0217e-01, -9.5533e-01, -6.0300e-01,  9.0229e-01],
         [ 1.9482e-01,  3.1558e-01, -2.7116e-01,  5.4285e-04]],

        [[ 4.0474e-01,  6.0414e-01,  1.6567e-01, -5.6019e-02],
         [ 5.8438e-01, -4.3327e-01,  2.1372e-01, -8.9602e-01]],

        [[-1.0465e-01, -7.5550e-01, -1.1882e-01,  8.0341e-01],
         [ 2.8364e-01, -4.7081e-01, -4.6782e-01,  7.3324e-01]],

        [[-3.0787e-01, -6.2524e-01,  5.3384e-01, -7.5075e-01],
         [ 2.7799e-01, -2.4057e-01,  4.5780e-01,  1.8433e-01]]],
       grad_fn=<StackBackward0>)
