In [12]:
import math

import torch

In [13]:
torch.set_printoptions(sci_mode=False, precision=6)
torch.manual_seed(42)

In [14]:
SEQ_LEN = 4
embedding_dim = 4
dk = 128

In [15]:
# 定义数据，形状(L, dk) dk -> 词向量维度
X = torch.randn(size=(SEQ_LEN, embedding_dim))

In [16]:
# 计算Q、K、V矩阵
Wq = torch.randn(size=(embedding_dim, dk), requires_grad=True)
Wk = torch.randn(size=(embedding_dim, dk), requires_grad=True)
Wv = torch.randn(size=(embedding_dim, dk), requires_grad=True)
Q = X @ Wq
K = X @ Wk
V = X @ Wv
print(Q)
print(Q.shape)

tensor([[ 0.423596,  3.922227,  0.722062,  3.840916, -3.196399,  1.392442,
          1.671251,  3.527405,  2.069108,  9.013926, -0.938350,  3.429983,
         -3.462946,  1.083040, -1.613586,  1.196529, -6.058063,  0.535812,
          0.205072,  1.133744,  1.748636, -0.739892,  0.302385,  0.302742,
         -2.546403,  5.718063,  0.403321, -0.737096, -6.963229,  6.626391,
          1.068820,  1.262899, -0.303750, -4.125079,  0.675463, -3.148711,
         -3.704368,  1.152661, -6.743222, -5.550589, -4.766078, -1.314648,
         -3.188165,  3.018471,  0.861357,  0.173495, -1.751478,  4.408199,
          8.727873, -1.391478,  8.765864, -0.871616,  0.242554,  2.554006,
          0.027634,  2.807178, -2.559477,  5.039980, -1.200962, -1.563010,
          1.612872,  2.535391, -0.179999, -2.975058, -2.702163, -0.567739,
         -2.750217, -2.059346,  1.431884, -1.490961,  4.289475, -0.347456,
          3.620867,  1.504248, -5.621109,  5.893834, -7.971818, -7.061675,
         -0.718465,  5.43

In [22]:
# 计算注意力评分
scores = Q @ K.T / math.sqrt(dk)
# scores = Q @ K.T
print(scores)

tensor([[ 6.817133, 13.044707,  6.938802, -2.126910],
        [ 4.970392,  5.277104,  1.975619, -2.462973],
        [ 4.954456,  8.677926,  5.670417, -2.002365],
        [-0.786902, -5.131322, -2.118544, -0.239252]], grad_fn=<DivBackward0>)


In [23]:
# 计算注意力权重
weights = torch.softmax(scores, dim=-1)
print(weights)

tensor([[0.001966, 0.995813, 0.002220, 0.000000],
        [0.415009, 0.563976, 0.020770, 0.000245],
        [0.022495, 0.931456, 0.046028, 0.000021],
        [0.332645, 0.004317, 0.087833, 0.575205]], grad_fn=<SoftmaxBackward0>)


In [24]:
# 计算上下文向量
vectors = weights @ V
print(vectors)
print(vectors.shape)

tensor([[ 1.293672, -0.646962, -1.913032,  1.709802,  0.878047,  0.525694,
         -5.892041, -1.625046,  2.446215,  2.785657,  0.387842,  0.870667,
          2.103563,  2.662470, -3.944352,  1.307998, -1.833394,  0.035501,
          0.871918, -1.487659, -0.142376,  0.698286,  4.262377,  0.771683,
          1.020658, -2.938719, -0.213681, -1.202820, -1.508520, -2.652560,
         -0.070029, -5.387192, -0.058879, -1.018371, -3.629228, -0.444052,
         -1.320453, -2.653985,  2.117146,  0.025982, -0.711171, -0.437172,
          2.737568, -3.100108,  1.162864,  0.384719, -1.211030,  0.677806,
          1.993784, -1.599981, -2.369471, -1.446362,  1.696553,  0.648183,
          1.574657,  0.781499,  2.416789,  2.392939, -0.548871, -3.215230,
         -0.539083, -4.887652,  4.853743,  1.524530, -1.994552,  5.630676,
          1.036547, -1.022667, -2.055771,  3.290280, -0.578899,  2.264876,
         -1.808878,  2.204885,  3.326612, -1.315454,  2.190131, -0.332152,
         -0.356571, -1.51

In [20]:
# 模拟损失计算，并反向传播
loss = vectors.sum()
loss.backward()

In [21]:
print(Wq.grad)

tensor([[  0.071353,  -1.652862,   0.346767,  -2.417847,   0.374094,  -0.658954,
          -0.726690,  -0.139917,  -1.588614,  -0.229967,  -1.517290,  -0.080269,
           0.012695,   2.159184,   0.976125,  -2.876785,   2.732152,  -2.133430,
          -0.500095,  -1.831335,  -1.338060,   0.982707,   0.415523,  -0.575522,
          -3.375756,  -1.104189,   1.442015,  -2.103238,  -0.022877,  -0.787857,
          -0.799014,   1.750712,   0.701571,   1.578260,   0.713374,   4.475804,
           0.752499,  -1.007644,   0.104099,   1.776275,   0.620828,  -0.468436,
           2.347582,  -0.270520,  -2.289569,   5.155013,   1.663195,   1.623754,
          -0.004711,   0.402086,   2.520463,   2.186105,  -1.198835,   1.731683,
          -1.415403,  -0.686537,  -2.403417,  -0.575215,  -0.085791,  -0.872751,
          -0.491275,   0.897915,   0.661267,   1.620771,   1.822877,  -0.194968,
           2.234689,   3.354229,   0.664852,   0.964543,   0.935854,  -0.069588,
          -0.193926,   1.085