In [1]:
import torch
import torch.nn as nn
from gensim.models import KeyedVectors

## 词嵌入层

In [2]:
embedding = nn.Embedding(num_embeddings=10000, embedding_dim=100)

In [3]:
print(embedding.weight.shape)

torch.Size([10000, 100])


## 加载已训练好的词向量

In [4]:
# 1. 记载KeyedVectors模型
kv_model = KeyedVectors.load_word2vec_format('data/word2vec.kv')

In [5]:
num_embeddings = len(kv_model.index_to_key)
print(num_embeddings)
embedding_dim = kv_model.vector_size
print(embedding_dim)

34576
100


In [6]:
# 2. 定义嵌入层，记载
# embedding = nn.Embedding(num_embeddings=num_embeddings, embedding_dim=embedding_dim)
embedding = nn.Embedding.from_pretrained(
    embeddings=torch.tensor(kv_model.vectors),
    freeze=False,
)

## 嵌入层测试

In [7]:
# 1. 获取词表
word2id = kv_model.key_to_index
print(word2id)

{'，': 0, '的': 1, '。': 2, '了': 3, '！': 4, '很': 5, '是': 6, '我': 7, '也': 8, '好': 9, '不': 10, ',': 11, '都': 12, '就': 13, '买': 14, '不错': 15, '还': 16, '在': 17, '有': 18, '没有': 19, '酒店': 20, '用': 21, '.': 22, '京东': 23, '和': 24, '说': 25, '房间': 26, '给': 27, '可以': 28, '、': 29, '这': 30, '就是': 31, '到': 32, '非常': 33, '一个': 34, '感觉': 35, '还是': 36, '？': 37, '没': 38, '这个': 39, '服务': 40, '质量': 41, '人': 42, '比较': 43, '上': 44, '苹果': 45, '要': 46, '看': 47, '去': 48, '喜欢': 49, '东西': 50, '太': 51, '不是': 52, '又': 53, '小': 54, '但': 55, '我们': 56, '大': 57, '价格': 58, '让': 59, '什么': 60, '但是': 61, '吧': 62, '你': 63, '差': 64, '住': 65, '而且': 66, '多': 67, '个': 68, '…': 69, '知道': 70, '自己': 71, '再': 72, '才': 73, '满意': 74, '会': 75, '啊': 76, '有点': 77, '：': 78, '对': 79, '比': 80, '不好': 81, '挺': 82, '问题': 83, '快递': 84, '收到': 85, '能': 86, '吃': 87, '手机': 88, '2': 89, '裤子': 90, '来': 91, '时候': 92, '一般': 93, '快': 94, '还有': 95, '一样': 96, '?': 97, '入住': 98, '方便': 99, '后': 100, '真的': 101, '这样': 102, '一直': 103, '~': 104, '包装': 105, '；': 

In [8]:
# 2. 获取输入，id
input_id = word2id['地铁']
print(input_id)

1519


In [9]:
input = torch.tensor(input_id)
print(input)

tensor(1519)


In [10]:
# 3. 前向传播
vector = embedding(input)
print(vector)

tensor([ 0.1112,  0.2051, -0.2167,  0.4443, -0.0931, -1.0754,  0.7010,  0.5942,
        -0.2342,  0.2335, -0.2157, -0.3444,  0.2757, -0.2126,  0.7693, -0.1191,
         0.2921, -0.7395, -0.0621, -0.2388,  0.4686, -0.0704,  0.3643, -0.2953,
        -0.3547,  0.2726,  0.1722,  0.0063, -0.3274, -0.0042,  0.1460,  0.0944,
         0.3869, -0.4889,  0.2968,  0.0867,  0.1583,  0.0570,  0.0777, -0.0135,
        -0.9707,  0.1810,  0.0667, -0.2028,  0.3929, -0.2149,  0.1761,  0.5528,
         0.1650,  0.3421, -0.0162,  0.0602, -0.5011,  0.1961,  0.1955,  0.1760,
         0.4512,  0.2017, -0.5176, -0.0358, -0.0404,  0.4505,  0.3043,  0.0230,
         0.5148, -0.0341, -0.1230,  0.8019,  0.3476,  0.5646,  0.1935, -0.2956,
        -0.0037, -0.1569, -0.3755,  0.2249, -0.0689, -0.0401,  0.1326, -0.4391,
        -0.1452, -0.3576, -0.0720,  0.2543, -0.1534,  0.1833,  0.2142,  0.0751,
         0.3836,  0.4057,  0.4188, -0.3814,  0.1498,  0.4264,  0.2342,  0.2329,
        -0.2985, -0.2150,  0.4471, -0.13

## 测试示例

In [12]:
import jieba

In [19]:
# text = "我喜欢乘坐地铁"
text = "我喜欢乘坐宇宙飞船"

In [20]:
# 1. 分词
tokens = jieba.lcut(text)
print(tokens)

['我', '喜欢', '乘坐', '宇宙飞船']


In [21]:
# 2. 编码（id化）
ids = [word2id[token] for token in tokens]
print(ids)

KeyError: '宇宙飞船'

In [16]:
# 3. 定义模型输入
input = torch.tensor(ids)
print(input)

tensor([   7,   49, 5819, 1519])


In [18]:
# 4. 模型前向传播
vectors = embedding(input)
print(vectors)
print(vectors.shape)

tensor([[ 9.4635e-03, -3.1463e-03,  8.2943e-02,  3.0667e-02, -2.8576e-02,
         -4.2073e-01,  3.5758e-01, -5.0012e-03, -2.1629e-02, -4.3533e-01,
         -1.2181e-01, -1.7759e-01,  3.3101e-02, -4.1582e-01, -2.3993e-01,
         -2.6535e-01, -1.5473e-01, -2.2884e-01, -7.7821e-02, -5.8616e-01,
          1.5623e-01,  4.1398e-02,  1.1106e-01,  1.6543e-01, -1.6341e-01,
         -9.8210e-02, -1.6425e-01,  3.8751e-01, -3.1704e-01, -2.8591e-01,
          7.0201e-01,  2.7574e-01,  2.2783e-01, -1.9032e-01,  1.4009e-01,
          4.9396e-02,  4.2798e-01, -3.0389e-01, -1.3029e-01, -4.5366e-01,
          2.9115e-01, -2.6140e-02, -8.9928e-02,  4.9404e-02,  1.9363e-01,
          2.6641e-01, -1.7250e-01, -1.9334e-01, -4.3547e-02,  2.7517e-01,
         -2.9089e-01, -6.4154e-02,  1.7849e-01,  1.4081e-01, -3.0828e-01,
          2.3650e-01,  1.9576e-01, -1.1902e-01, -8.3678e-02,  3.1620e-01,
          2.5313e-01, -6.7256e-02, -2.3447e-01, -4.0031e-01,  1.3148e-03,
          3.1803e-01,  1.2913e-01,  4.

## OOV问题（未登录词）

In [28]:
# 在词表中增加处理OOV的特殊token
unk_token = '<UNK>'
id2word = [unk_token] + kv_model.index_to_key
print(id2word)

['<UNK>', '，', '的', '。', '了', '！', '很', '是', '我', '也', '好', '不', ',', '都', '就', '买', '不错', '还', '在', '有', '没有', '酒店', '用', '.', '京东', '和', '说', '房间', '给', '可以', '、', '这', '就是', '到', '非常', '一个', '感觉', '还是', '？', '没', '这个', '服务', '质量', '人', '比较', '上', '苹果', '要', '看', '去', '喜欢', '东西', '太', '不是', '又', '小', '但', '我们', '大', '价格', '让', '什么', '但是', '吧', '你', '差', '住', '而且', '多', '个', '…', '知道', '自己', '再', '才', '满意', '会', '啊', '有点', '：', '对', '比', '不好', '挺', '问题', '快递', '收到', '能', '吃', '手机', '2', '裤子', '来', '时候', '一般', '快', '还有', '一样', '?', '入住', '方便', '后', '真的', '这样', '一直', '~', '包装', '；', '蒙牛', '!', '物流', '着', '速度', '过', '以后', '不过', '3', '舒服', '客服', '特别', '一次', '不能', '穿', '*', '很多', '他', '味道', '送', '1', '）', '现在', '一点', '因为', '前台', '购买', '下次', '屏幕', '觉得', '已经', '早餐', '差评', '（', '想', '本书', '中', '时', '不会', '垃圾', '月', '第一次', '里', '跟', '把', '这次', '这么', '值得', '支持', '如果', '被', '效果', '呢', '得', '4', '便宜', '应该', '“', '很快', '”', '最', '起来', '发现', '一', '点', '等', '所以', '高', '希望', '大家', '设施', '失望', '怎么', '

In [29]:
# 转换字典
word2id = { word:id for id, word in enumerate(id2word) }
print(word2id)

{'<UNK>': 0, '，': 1, '的': 2, '。': 3, '了': 4, '！': 5, '很': 6, '是': 7, '我': 8, '也': 9, '好': 10, '不': 11, ',': 12, '都': 13, '就': 14, '买': 15, '不错': 16, '还': 17, '在': 18, '有': 19, '没有': 20, '酒店': 21, '用': 22, '.': 23, '京东': 24, '和': 25, '说': 26, '房间': 27, '给': 28, '可以': 29, '、': 30, '这': 31, '就是': 32, '到': 33, '非常': 34, '一个': 35, '感觉': 36, '还是': 37, '？': 38, '没': 39, '这个': 40, '服务': 41, '质量': 42, '人': 43, '比较': 44, '上': 45, '苹果': 46, '要': 47, '看': 48, '去': 49, '喜欢': 50, '东西': 51, '太': 52, '不是': 53, '又': 54, '小': 55, '但': 56, '我们': 57, '大': 58, '价格': 59, '让': 60, '什么': 61, '但是': 62, '吧': 63, '你': 64, '差': 65, '住': 66, '而且': 67, '多': 68, '个': 69, '…': 70, '知道': 71, '自己': 72, '再': 73, '才': 74, '满意': 75, '会': 76, '啊': 77, '有点': 78, '：': 79, '对': 80, '比': 81, '不好': 82, '挺': 83, '问题': 84, '快递': 85, '收到': 86, '能': 87, '吃': 88, '手机': 89, '2': 90, '裤子': 91, '来': 92, '时候': 93, '一般': 94, '快': 95, '还有': 96, '一样': 97, '?': 98, '入住': 99, '方便': 100, '后': 101, '真的': 102, '这样': 103, '一直': 104, '~': 105, '包

In [33]:
# 修改词嵌入层
embedding_matrix = torch.cat([torch.zeros(1, kv_model.vector_size), torch.tensor(kv_model.vectors)]) # 通过torch.cat将零向量和原始词向量拼接起来，形成新的嵌入矩阵
embedding = nn.Embedding.from_pretrained(
    embeddings=embedding_matrix,
    freeze=False,
)
print(embedding.weight)

Parameter containing:
tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [-2.7764e-01,  4.4371e-02,  1.3744e-02,  ..., -1.4716e-01,
         -1.2358e-02,  2.3901e-02],
        [ 5.8257e-02,  4.4647e-02,  3.8535e-01,  ..., -4.4593e-02,
          1.2386e-01, -1.0723e-01],
        ...,
        [-8.9628e-04,  1.0426e-01, -3.1620e-02,  ..., -1.4727e-02,
          6.1372e-02, -1.2088e-01],
        [-1.3818e-04,  8.1116e-02, -4.4554e-03,  ...,  1.6634e-03,
          5.5193e-03, -9.6727e-02],
        [ 4.4499e-02,  9.6705e-02, -4.3875e-02,  ..., -3.1659e-02,
          7.3698e-03, -9.8877e-02]], requires_grad=True)


In [22]:
text = "我喜欢乘坐宇宙飞船"

In [23]:
# 1. 分词
tokens = jieba.lcut(text)
print(tokens)

['我', '喜欢', '乘坐', '宇宙飞船']


In [30]:
# 2. 编码（id化）
ids = [word2id.get(token, word2id[unk_token]) for token in tokens]
print(ids)

[8, 50, 5820, 0]


In [31]:
# 3. 定义模型输入
input = torch.tensor(ids)
print(input)

tensor([   8,   50, 5820,    0])


In [34]:
# 4. 模型前向传播
vectors = embedding(input)
print(vectors)
print(vectors.shape)

tensor([[ 9.4635e-03, -3.1463e-03,  8.2943e-02,  3.0667e-02, -2.8576e-02,
         -4.2073e-01,  3.5758e-01, -5.0012e-03, -2.1629e-02, -4.3533e-01,
         -1.2181e-01, -1.7759e-01,  3.3101e-02, -4.1582e-01, -2.3993e-01,
         -2.6535e-01, -1.5473e-01, -2.2884e-01, -7.7821e-02, -5.8616e-01,
          1.5623e-01,  4.1398e-02,  1.1106e-01,  1.6543e-01, -1.6341e-01,
         -9.8210e-02, -1.6425e-01,  3.8751e-01, -3.1704e-01, -2.8591e-01,
          7.0201e-01,  2.7574e-01,  2.2783e-01, -1.9032e-01,  1.4009e-01,
          4.9396e-02,  4.2798e-01, -3.0389e-01, -1.3029e-01, -4.5366e-01,
          2.9115e-01, -2.6140e-02, -8.9928e-02,  4.9404e-02,  1.9363e-01,
          2.6641e-01, -1.7250e-01, -1.9334e-01, -4.3547e-02,  2.7517e-01,
         -2.9089e-01, -6.4154e-02,  1.7849e-01,  1.4081e-01, -3.0828e-01,
          2.3650e-01,  1.9576e-01, -1.1902e-01, -8.3678e-02,  3.1620e-01,
          2.5313e-01, -6.7256e-02, -2.3447e-01, -4.0031e-01,  1.3148e-03,
          3.1803e-01,  1.2913e-01,  4.